server:
  servlet:
    contextPath: /api/v1
  port: 8991

springdoc:
  api-docs:
    path: /api-docs

db:
  name: ert
  uri: mongodb://localhost:27017

endpoint:
  locality: https://emiliaromagnaturismo.it/opendata/v1/localities
